### ISSUE TITLE
Attack screen

### ISSUE THREAD

**Issue by Plopptheblacke** [SkyWtkh/Stellar-New-Age#10]
Will v4 have an attack screen like where when u send an attack u get an animation or like an attack sent or anything like that

**Comment by SkyWtkh** [comment]
No, only the VIP version (private version)

**Comment by andress134** [comment]
> where can i get the VIP version?

hey don't pay for this shit. all scripts are free
almost scripts are coded by user node from nulled forum and HF him discord is Node#6354
more of these scrips are coded by node and sold long time ago
all scripts now got leaked and shared on all forums / tg channels
and u can see this scripts use old library like cloudscraper

**Comment by Plopptheblacke** [comment]
> > where can i get the VIP version?
> 
> hey don't pay for this shit. all scripts are free almost scripts are coded by user node from nulled forum and HF him discord is Node#6354 more of these scrips are coded by node and sold long time ago all scripts now got leaked and shared on all forums / tg channels and u can see this scripts use old library like cloudscraper

Hit me up on telegram t.me/daddyplopp if u can help me with sum code

**Comment by Xoosz** [comment]
Okay bro check Dms
