### ISSUE TITLE
Ascii problem

### ISSUE THREAD

**Issue by Plopptheblacke** [SkyWtkh/Stellar-New-Age#8]
Hello there do you know how to fix the problem where it says ascii code 128 sum with the colors not being able to load

**Comment by pl8g** [comment]
Your terminal has to accept ANSI colors so that the colors can be seen

**Comment by SkyWtkh** [comment]
answering the first question: the truth is that your problem has never happened to me (not even in google cloud shell, kali and my vps) maybe it is some problem with your terminal. I recommend that if it continues like this, you change the terminal
